ERROR - 2024-02-07 04:45:20 --> mysqli_sql_exception: Column 'user_name' cannot be null in C:\xampp\htdocs\ApiIntegration\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ApiIntegration\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ap...', 0)
#1 C:\xampp\htdocs\ApiIntegration\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ap...')
#2 C:\xampp\htdocs\ApiIntegration\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ap...')
#3 C:\xampp\htdocs\ApiIntegration\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ap...', Array, false)
#4 C:\xampp\htdocs\ApiIntegration\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ApiIntegration\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ApiIntegration\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\ApiIntegration\app\Controllers\Auth.php(36): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php(941): App\Controllers\Auth->createuser()
#9 C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ApiIntegration\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-02-07 04:45:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'user_name' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (:user_name:, :user_email:, :user_phone:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Auth.php(36): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->createuser()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 04:45:20 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'user_name' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (NULL, NULL, NULL)')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (NULL, NULL, NULL)')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (:user_name:, :user_email:, :user_phone:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Auth.php(36): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->createuser()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 04:45:20 --> [Caused by] mysqli_sql_exception: Column 'user_name' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (NULL, NULL, NULL)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (NULL, NULL, NULL)')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (NULL, NULL, NULL)')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (:user_name:, :user_email:, :user_phone:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Auth.php(36): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->createuser()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 04:45:41 --> Error: Call to undefined function App\Controllers\respondCreated()
in APPPATH\Controllers\Auth.php on line 37.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->createuser()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 05:03:42 --> ErrorException: Undefined variable $response
in APPPATH\Controllers\Auth.php on line 58.
 1 APPPATH\Controllers\Auth.php(58): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $response', 'C:\\xampp\\htdocs\\ApiIntegration\\app\\Controllers\\Auth.php', 58)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->showSingleuserList('1')
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 05:27:23 --> ErrorException: Array to string conversion
in SYSTEMPATH\Database\Query.php on line 327.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\xampp\\htdocs\\ApiIntegration\\system\\Database\\Query.php', 327)
 2 SYSTEMPATH\Database\Query.php(327): implode(',', [...])
 3 SYSTEMPATH\Database\Query.php(308): CodeIgniter\Database\Query->matchNamedBinds('DELETE FROM `apiintegration`
WHERE `user_id` IN :user_id:', [...])
 4 SYSTEMPATH\Database\Query.php(159): CodeIgniter\Database\Query->compileBinds()
 5 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\Query->getQuery()
 6 SYSTEMPATH\Database\BaseBuilder.php(2787): CodeIgniter\Database\BaseConnection->query('DELETE FROM `apiintegration`
WHERE `user_id` IN :user_id:', [...], false)
 7 SYSTEMPATH\Model.php(453): CodeIgniter\Database\BaseBuilder->delete()
 8 SYSTEMPATH\BaseModel.php(1117): CodeIgniter\Model->doDelete([...], false)
 9 APPPATH\Controllers\Auth.php(74): CodeIgniter\BaseModel->delete([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->deletesinglelist('2')
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 05:28:31 --> ErrorException: Array to string conversion
in SYSTEMPATH\Database\Query.php on line 327.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\xampp\\htdocs\\ApiIntegration\\system\\Database\\Query.php', 327)
 2 SYSTEMPATH\Database\Query.php(327): implode(',', [...])
 3 SYSTEMPATH\Database\Query.php(308): CodeIgniter\Database\Query->matchNamedBinds('DELETE FROM `apiintegration`
WHERE `user_id` IN :user_id:', [...])
 4 SYSTEMPATH\Database\Query.php(159): CodeIgniter\Database\Query->compileBinds()
 5 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\Query->getQuery()
 6 SYSTEMPATH\Database\BaseBuilder.php(2787): CodeIgniter\Database\BaseConnection->query('DELETE FROM `apiintegration`
WHERE `user_id` IN :user_id:', [...], false)
 7 SYSTEMPATH\Model.php(453): CodeIgniter\Database\BaseBuilder->delete()
 8 SYSTEMPATH\BaseModel.php(1117): CodeIgniter\Model->doDelete([...], false)
 9 APPPATH\Controllers\Auth.php(74): CodeIgniter\BaseModel->delete([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->deletesinglelist('2')
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 05:28:59 --> ErrorException: Array to string conversion
in SYSTEMPATH\Database\Query.php on line 327.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\xampp\\htdocs\\ApiIntegration\\system\\Database\\Query.php', 327)
 2 SYSTEMPATH\Database\Query.php(327): implode(',', [...])
 3 SYSTEMPATH\Database\Query.php(308): CodeIgniter\Database\Query->matchNamedBinds('DELETE FROM `apiintegration`
WHERE `user_id` IN :user_id:', [...])
 4 SYSTEMPATH\Database\Query.php(159): CodeIgniter\Database\Query->compileBinds()
 5 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\Query->getQuery()
 6 SYSTEMPATH\Database\BaseBuilder.php(2787): CodeIgniter\Database\BaseConnection->query('DELETE FROM `apiintegration`
WHERE `user_id` IN :user_id:', [...], false)
 7 SYSTEMPATH\Model.php(453): CodeIgniter\Database\BaseBuilder->delete()
 8 SYSTEMPATH\BaseModel.php(1117): CodeIgniter\Model->doDelete([...], false)
 9 APPPATH\Controllers\Auth.php(75): CodeIgniter\BaseModel->delete([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->deletesinglelist('2')
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 05:31:15 --> ErrorException: Array to string conversion
in APPPATH\Controllers\Auth.php on line 73.
 1 APPPATH\Controllers\Auth.php(73): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\xampp\\htdocs\\ApiIntegration\\app\\Controllers\\Auth.php', 73)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->deletesinglelist('2')
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-07 05:54:02 --> mysqli_sql_exception: Column 'user_name' cannot be null in C:\xampp\htdocs\ApiIntegration\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ApiIntegration\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ap...', 0)
#1 C:\xampp\htdocs\ApiIntegration\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ap...')
#2 C:\xampp\htdocs\ApiIntegration\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ap...')
#3 C:\xampp\htdocs\ApiIntegration\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ap...', Array, false)
#4 C:\xampp\htdocs\ApiIntegration\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ApiIntegration\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ApiIntegration\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\ApiIntegration\app\Controllers\Auth.php(36): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php(941): App\Controllers\Auth->createuser()
#9 C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ApiIntegration\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-02-07 05:54:02 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'user_name' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (:user_name:, :user_email:, :user_phone:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Auth.php(36): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->createuser()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 05:54:02 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'user_name' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (NULL, NULL, NULL)')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (NULL, NULL, NULL)')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (:user_name:, :user_email:, :user_phone:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Auth.php(36): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->createuser()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 05:54:02 --> [Caused by] mysqli_sql_exception: Column 'user_name' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (NULL, NULL, NULL)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (NULL, NULL, NULL)')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (NULL, NULL, NULL)')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (:user_name:, :user_email:, :user_phone:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Auth.php(36): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->createuser()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-07 05:57:44 --> mysqli_sql_exception: Column 'user_phone' cannot be null in C:\xampp\htdocs\ApiIntegration\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ApiIntegration\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ap...', 0)
#1 C:\xampp\htdocs\ApiIntegration\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ap...')
#2 C:\xampp\htdocs\ApiIntegration\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ap...')
#3 C:\xampp\htdocs\ApiIntegration\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ap...', Array, false)
#4 C:\xampp\htdocs\ApiIntegration\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ApiIntegration\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ApiIntegration\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\ApiIntegration\app\Controllers\Auth.php(36): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php(941): App\Controllers\Auth->createuser()
#9 C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ApiIntegration\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-02-07 05:57:44 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'user_phone' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (:user_name:, :user_email:, :user_phone:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Auth.php(36): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->createuser()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 05:57:44 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'user_phone' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (\'\', \'\', NULL)')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (\'\', \'\', NULL)')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (:user_name:, :user_email:, :user_phone:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Auth.php(36): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->createuser()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 05:57:44 --> [Caused by] mysqli_sql_exception: Column 'user_phone' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (\'\', \'\', NULL)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (\'\', \'\', NULL)')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (\'\', \'\', NULL)')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (:user_name:, :user_email:, :user_phone:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Auth.php(36): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->createuser()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 06:06:23 --> ErrorException: Attempt to read property "name" on null
in APPPATH\Controllers\Auth.php on line 33.
 1 APPPATH\Controllers\Auth.php(33): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "name" on null', 'C:\\xampp\\htdocs\\ApiIntegration\\app\\Controllers\\Auth.php', 33)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 06:10:20 --> Error: Call to undefined function App\Controllers\json_validate()
in APPPATH\Controllers\Auth.php on line 32.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->create()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 10:28:22 --> ArgumentCountError: Too few arguments to function App\Controllers\Auth::updateuserlist(), 0 passed in C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php on line 941 and exactly 1 expected
in APPPATH\Controllers\Auth.php on line 126.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->updateuserlist()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-07 10:33:26 --> mysqli_sql_exception: Column 'user_name' cannot be null in C:\xampp\htdocs\ApiIntegration\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ApiIntegration\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ap...', 0)
#1 C:\xampp\htdocs\ApiIntegration\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ap...')
#2 C:\xampp\htdocs\ApiIntegration\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ap...')
#3 C:\xampp\htdocs\ApiIntegration\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ap...', Array, false)
#4 C:\xampp\htdocs\ApiIntegration\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ApiIntegration\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ApiIntegration\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\ApiIntegration\app\Controllers\Auth.php(83): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php(941): App\Controllers\Auth->createuser()
#9 C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ApiIntegration\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-02-07 10:33:27 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'user_name' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (:user_name:, :user_email:, :user_phone:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Auth.php(83): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->createuser()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 10:33:27 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'user_name' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (NULL, NULL, NULL)')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (NULL, NULL, NULL)')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (:user_name:, :user_email:, :user_phone:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Auth.php(83): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->createuser()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 10:33:27 --> [Caused by] mysqli_sql_exception: Column 'user_name' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (NULL, NULL, NULL)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (NULL, NULL, NULL)')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (NULL, NULL, NULL)')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `apiintegration` (`user_name`, `user_email`, `user_phone`) VALUES (:user_name:, :user_email:, :user_phone:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Auth.php(83): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->createuser()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 10:33:49 --> CodeIgniter\HTTP\Exceptions\HTTPException: Failed to parse JSON string. Error: Syntax error
in SYSTEMPATH\HTTP\IncomingRequest.php on line 588.
 1 SYSTEMPATH\HTTP\IncomingRequest.php(588): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidJSON('Syntax error')
 2 APPPATH\Controllers\Auth.php(31): CodeIgniter\HTTP\IncomingRequest->getJSON()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->create()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 10:48:05 --> ArgumentCountError: Too few arguments to function App\Controllers\Auth::updateuserlist(), 0 passed in C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php on line 941 and exactly 1 expected
in APPPATH\Controllers\Auth.php on line 126.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->updateuserlist()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 10:49:22 --> ArgumentCountError: Too few arguments to function App\Controllers\Auth::updateuserlist(), 0 passed in C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php on line 941 and exactly 1 expected
in APPPATH\Controllers\Auth.php on line 126.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->updateuserlist()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 10:49:57 --> ArgumentCountError: Too few arguments to function App\Controllers\Auth::updateuserlist(), 0 passed in C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php on line 941 and exactly 1 expected
in APPPATH\Controllers\Auth.php on line 126.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->updateuserlist()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 10:50:11 --> ArgumentCountError: Too few arguments to function App\Controllers\Auth::updateuserlist(), 0 passed in C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php on line 941 and exactly 1 expected
in APPPATH\Controllers\Auth.php on line 126.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->updateuserlist()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 10:51:18 --> ArgumentCountError: Too few arguments to function App\Controllers\Auth::updateuserlist(), 0 passed in C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php on line 941 and exactly 1 expected
in APPPATH\Controllers\Auth.php on line 126.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->updateuserlist()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 10:51:28 --> ArgumentCountError: Too few arguments to function App\Controllers\Auth::updateuserlist(), 0 passed in C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php on line 941 and exactly 1 expected
in APPPATH\Controllers\Auth.php on line 126.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->updateuserlist()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 10:51:52 --> ArgumentCountError: Too few arguments to function App\Controllers\Auth::updateuserlist(), 0 passed in C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php on line 941 and exactly 1 expected
in APPPATH\Controllers\Auth.php on line 126.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->updateuserlist()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 10:53:24 --> ArgumentCountError: Too few arguments to function App\Controllers\Auth::updateuserlist(), 0 passed in C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php on line 941 and exactly 1 expected
in APPPATH\Controllers\Auth.php on line 126.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->updateuserlist()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 11:40:57 --> ArgumentCountError: Too few arguments to function App\Controllers\Auth::updateuserlist(), 0 passed in C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php on line 941 and exactly 1 expected
in APPPATH\Controllers\Auth.php on line 126.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->updateuserlist()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 11:41:01 --> ArgumentCountError: Too few arguments to function App\Controllers\Auth::updateuserlist(), 0 passed in C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php on line 941 and exactly 1 expected
in APPPATH\Controllers\Auth.php on line 126.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->updateuserlist()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 13:19:13 --> ArgumentCountError: Too few arguments to function App\Controllers\Auth::updateuserlist(), 0 passed in C:\xampp\htdocs\ApiIntegration\system\CodeIgniter.php on line 941 and exactly 1 expected
in APPPATH\Controllers\Auth.php on line 126.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->updateuserlist()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-07 13:30:12 --> ErrorException: Undefined variable $id
in APPPATH\Controllers\Auth.php on line 133.
 1 APPPATH\Controllers\Auth.php(133): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $id', 'C:\\xampp\\htdocs\\ApiIntegration\\app\\Controllers\\Auth.php', 133)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Auth->updateuserlist('8')
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
